### ISSUE TITLE
[0-3] Escopo do Projeto e Descrição do Readme

### ISSUE THREAD

**Issue by brailog** [vsla/BugHunter#1]
"Ata da primeira reunião com cliente ou registro da primeira reunião de definição de escopo do projeto; artefato salvo no repositório"

**Comment by brailog** [comment]
Criação do readme também

**Comment by vsla** [comment]
Poderíamos adicionar no README algumas coisas

- [ ] Sumário
   - [ ] Descrição do projeto
   - [ ] Equipe com os emails do lado
   - [ ] Plano de Desenvolvimento
       - [ ] Metodologia de Desenvolvimento
       - [ ] Funções na equipe

O que achas @brailog
