### ISSUE TITLE
[1-4] CRUD Projeto

### ISSUE THREAD

**Issue by aas8** [vsla/BugHunter#25]
- [x] Get Projeto

- [x] Post Projeto

- [x] Patch Projeto

**Comment by vsla** [comment]
Falta fazer
- [ ] Get all projects by company id

**Comment by vsla** [comment]
> Falta fazer
> 
> * [ ]  Get all projects by company id

Isso vai ser uma nova atividade!

**Comment by vsla** [comment]
Foi finalizado no repositório do backend
https://github.com/brailog/backend-bxh/i
