### ISSUE TITLE
feedback it#0

### ISSUE THREAD

**Issue by viniciusgiles** [vsla/BugHunter#41]
Olá! Perdão pelo atraso enorme nas correções de vocês. Aqui vai um feedback detalhado da iteração #0:

### História de usuários
- [x] Entrega no prazo da iteração
- [x] Formato (como... gostaria... para) (5/5)
- [x] Descrição das histórias (5/5)
- **Nota**: 10/10

### Ata da reunião com o cliente
- [ ] ~Entrega no prazo da iteração~ ([2 dias de atraso](https://github.com/vsla/BugHunter/commit/e5ae570fab2aaefdc49d9eef4212a6c26c6e8b0b) -4 pontos)
- [x] Participantes da reunião (2/2)
- [x] Tópicos discutidos (4/4)
- [x] O que foi definido (4/4)
- **Nota**: 6/10
- **Observação**: se possível criar arquivos para as atas de reunião dividido por iteração em vez de usar um único arquivo para todas as atas.

### Mockups e storyboard
- [x] Entrega no prazo da iteração
- [x] Esboço sequencial
- [x] Demonstração de telas
- **Nota**: 10/10

### Prenchimento do github
- [x] Nome do projeto (1/1)
- [x] Descrição do Produto (3/3)
- [x] Justificativa do Projeto (3/3)
- [x] Especificação do papel de cada membro (3/3)
- **Nota**: 10/10

### Postmortem
- [x] Entrega no prazo da iteração
- [x] Período (0.5/0.5)
- [x] O que estava planejado (1.9/1.9)
- [x] O que foi feito (1.9/1.9)
- [x] O que não foi feito (1.9/1.9)
- [x] O que está planejado pra próxima iteração (1.9/1.9)
- [x] Lições aprendidas (1.9/1.9)
- [x] Markdown
- **Nota**: 10/10
- **Observação**: favor criar o postmortem seguindo o [formato predefinido pelo professor](https://github.com/IF977/monitoria-if977-SI/blob/master/Postmortem.md).

**Comment by vsla** [comment]
Valeu!
