### ISSUE TITLE
feedback it#2: postmortem

### ISSUE THREAD

**Issue by viniciusgiles** [vsla/BugHunter#75]
### Postmortem
- [x] Entrega no prazo da iteração (nota máxima: 10)
- [x] Período (0.5/0.5)
- [x] O que estava planejado (1.9/1.9)
- [x] O que foi feito (1.9/1.9)
- [x] O que não foi feito (1.9/1.9)
- [x] O que está planejado pra próxima iteração (1.9/1.9)
- [x] Lições aprendidas (1.9/1.9)
- [x] Markdown
- **Nota**: 10/10
- **Observação**: trocar `em andamento` por `o que não foi feito` para seguir o padrão.

**Comment by vsla** [comment]
Valeu pelo **Feedbak** !!

@gilesv, não entendi muito bem a parte da observação. Seria para colocar  `o que não foi feito` onde? No comentário? No título da branch? Ou no Postmortem?
